package com.keyy.app;
public class WordBank {

    public static final String[] EASY = {
        "the", "and", "for", "are", "but", "not", "you", "all", "can", "her",
        "was", "one", "our", "out", "day", "get", "has", "him", "his", "how",
        "man", "new", "now", "old", "see", "two", "way", "who", "boy", "did",
        "its", "let", "put", "say", "she", "too", "use", "big", "cat", "dog",
        "red", "run", "sit", "sun", "top", "win", "yes", "ago", "air", "ask",
        "car", "cup", "eat", "egg", "fly", "hat", "hit", "hot", "ice", "jam",
        "key", "leg", "map", "net", "oil", "owl", "pen", "pie", "row", "sad",
        "sky", "ten", "bed", "box", "bus", "cut", "dry", "far", "fat", "few",
        "fun", "gas", "got", "gym", "job", "law", "lay", "mix", "mud", "nap",
        "odd", "off", "own", "pay", "pig", "pit", "pop", "pot", "rub", "rug",
        "set", "sip", "six", "ski", "son", "spa", "spy", "tab", "tan", "tap",
        "tax", "tea", "tin", "tip", "toe", "ton", "toy", "tub", "tug", "van",
        "wax", "web", "wet", "wit", "yam", "zip", "zoo", "arm", "bay", "bit",
        "bun", "den", "dew", "dim", "dip", "dot", "dug", "elm", "eve", "ewe",
        "fad", "fax", "fed", "fen", "foe", "fog", "gap", "gel", "gem", "gin",
        "gig", "gnu", "gut", "hay", "hem", "hen", "hub", "hug", "hum", "hut"
    };

    public static final String[] NORMAL = {
        "about", "above", "after", "again", "along", "among", "began", "below",
        "black", "blood", "board", "break", "bring", "built", "carry", "cause",
        "chain", "chair", "chart", "check", "child", "class", "clean", "clear",
        "clock", "close", "color", "count", "cover", "crash", "cross", "curve",
        "daily", "dance", "death", "depth", "doubt", "dream", "drive", "early",
        "earth", "eight", "enemy", "enjoy", "enter", "equal", "error", "every",
        "exact", "faith", "false", "fancy", "field", "fight", "final", "first",
        "fixed", "floor", "focus", "force", "found", "frame", "fresh", "front",
        "fruit", "glass", "grace", "grade", "grain", "grand", "grant", "grass",
        "great", "green", "group", "guard", "guess", "guest", "guide", "happy",
        "heard", "heart", "heavy", "hence", "house", "human", "ideal", "image",
        "inner", "input", "issue", "joint", "judge", "juice", "large", "laugh",
        "layer", "learn", "legal", "level", "light", "limit", "local", "logic",
        "lower", "lucky", "magic", "major", "match", "media", "metal", "minor",
        "model", "money", "month", "moral", "motor", "mouth", "music", "night",
        "noble", "noise", "north", "noted", "novel", "nurse", "occur", "offer",
        "often", "order", "other", "owner", "paint", "panel", "paper", "party",
        "peace", "phone", "photo", "pilot", "place", "plain", "plane", "plant",
        "plate", "point", "power", "press", "price", "pride", "prime", "print",
        "prior", "prize", "proof", "proud", "prove", "queen", "quest", "quick",
        "quiet", "quote", "raise", "range", "rapid", "ratio", "reach", "ready",
        "realm", "refer", "reply", "right", "rigid", "rival", "river", "robot",
        "round", "route", "ruler", "rural", "saint", "scale", "scene", "score",
        "scout", "sense", "serve", "seven", "shade", "shake", "shame", "share",
        "sharp", "shift", "shirt", "shock", "shoot", "shore", "short", "shout",
        "sight", "since", "sixth", "skill", "sleep", "slice", "slide", "small",
        "smart", "smell", "smile", "smoke", "solid", "solve", "sound", "south",
        "space", "spare", "spark", "speak", "speed", "spend", "spine", "split",
        "sport", "spray", "squad", "stack", "staff", "stage", "stair", "stamp",
        "stand", "stark", "start", "state", "steam", "steel", "stick", "still",
        "stock", "stone", "store", "storm", "story", "strip", "study", "stuff",
        "style", "sugar", "super", "surge", "swear", "sweet", "swift", "swing",
        "sword", "table", "taste", "teach", "teeth", "thank", "theme", "thick",
        "thing", "think", "third", "three", "throw", "tight", "timer", "tired",
        "title", "today", "token", "topic", "total", "touch", "tough", "tower",
        "track", "trade", "trail", "train", "trait", "treat", "trend", "trial",
        "truck", "truly", "trust", "truth", "twice", "twist", "ultra", "under",
        "union", "unity", "until", "upper", "usage", "usual", "valid", "value",
        "video", "viral", "visit", "vital", "vocal", "voice", "waste", "watch",
        "water", "weave", "wheat", "where", "which", "while", "white", "whole",
        "whose", "wider", "width", "women", "world", "worry", "worse", "worst",
        "would", "wound", "write", "wrong", "wrote", "yield", "young", "youth"
    };

    public static final String[] HARD = {
        "achievement", "acknowledge", "acquisition", "administration",
        "approximately", "architecture", "breakthrough", "bureaucratic",
        "catastrophic", "circumstances", "collaboration", "communication",
        "complications", "comprehensive", "concentrated", "configuration",
        "consciousness", "consequences", "contemporary", "controversial",
        "crystallized", "deliberately", "dependencies", "determination",
        "developmental", "differential", "distinguished", "encyclopedia",
        "enlightenment", "entertainment", "environmental", "establishment",
        "examination", "extraordinary", "facilitation", "functionality",
        "globalization", "governmental", "hallucination", "hypothetical",
        "identification", "implementation", "inconsistency", "infrastructure",
        "insignificant", "instantaneous", "intellectual", "international",
        "investigation", "justification", "knowledgeable", "liberalization",
        "manifestation", "miscellaneous", "modernization", "multiplication",
        "nevertheless", "notification", "opportunities", "organizational",
        "overwhelming", "parliamentary", "participation", "particularly",
        "philosophical", "physiological", "possibilities", "predominantly",
        "prescription", "presentation", "prioritization", "privatization",
        "proportional", "psychological", "qualification", "questionnaire",
        "rationalization", "recommendation", "reconciliation", "reconstruction",
        "redistribution", "reinforcement", "relationships", "reorganization",
        "representation", "responsibility", "revolutionary", "simultaneously",
        "sophisticated", "specification", "stabilization", "standardization",
        "straightforward", "subordination", "substantially", "superintendent",
        "supplementary", "sustainability", "systematically", "technological",
        "transformation", "transportation", "understanding", "unfortunately",
        "uncomfortable", "uncontrollable", "unemployment", "unimaginable",
        "unprecedented", "unsatisfactory", "vulnerability", "worthwhile",
        "abbreviation", "accommodation", "accountability", "accreditation",
        "accomplishment", "acknowledgment", "administrative", "advertisement",
        "affordability", "aforementioned", "aggravation", "anticipation",
        "approximation", "argumentation", "assassination", "authentication",
        "authorization", "automatically", "biodegradable", "biotechnology"
    };
}
